{{- range .Values.global.kmes }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-kme
spec:
  selector:
    app: {{ .name }}-kme
  ports:
  - protocol: TCP
    port: 65432
    targetPort: 65432 
    # TODO: a√±adir puerto grpc
---
{{- end }}
